apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontName }}
  labels:
    app: {{ .Values.frontName }}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: {{ .Values.frontName }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontName }}
    spec:
      containers:
      - name: {{ .Values.frontName }}
        image:{{ .Values.frontImg.name }}:{{ .Values.frontImg.tag}}
        ports:
        - containerPort: 3000