apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontName }}-service
spec:
  {% comment %} type: LoadBalancer {% endcomment %}
  selector:
    app: {{ .Values.frontName }}
  ports:
    {% comment %} - protocol: TCP {% endcomment %}
      port: 80
      targetPort: 3000