apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.apiAppName }}
  labels:
    app: {{ .Values.apiAppName }}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: {{ .Values.apiAppName }}
  template:
    metadata:
      labels:
        app: {{ .Values.apiAppName }}
    spec:
      containers:
      - name: {{ .Values.apiAppName }}
        image: {{ .Values.apiAppName }}:{{ .Values.apiImg.tag }}
        ports:
        - containerPort: 8080
    ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
        startupProbe:
          httpGet:
            path: /started
            port: 8080
          initialDelaySeconds: 0
          periodSeconds: 10
          failureThreshold: 30
        