apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apiAppName }}-service
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.apiAppName }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080