apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-api
  labels:
    app: mern-api
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: mern-api
  template:
    metadata:
      labels:
        app: mern-api
    spec:
      containers:
      - name: mern-api
        image: paularinze/mern-api:latest # Replace with your image
        ports:
        - containerPort: 8080

    ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
        startupProbe:
          httpGet:
            path: /started
            port: 8080
          initialDelaySeconds: 0
          periodSeconds: 10
          failureThreshold: 30
        